name: Compilar ISO PS1

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: lameguy64/psn00bsdk:latest

    steps:
    - name: Baixar código do repositório
      uses: actions/checkout@v4

    - name: Criar pasta de build e compilar
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=$PSN00BSDK/share/psn00bsdk/gcc-mipsel-none-elf.cmake ..
        make iso

    - name: Salvar ISO e CUE como artefato
      uses: actions/upload-artifact@v4
      with:
        name: PS1-Cubo3D-ISO
        path: |
          build/cubo_ps1_3d.iso
          build/cubo_ps1_3d.cue
